Explicitly support python 3.9->3.12
ASFHyP3/hyp3-sdk pull request #242
Opened 2023-11-01 21:13 UTC by jhkennedy

2023-11-01 21:15 UTC, jtherrmann commented on pyproject.toml
>      "Programming Language :: Python :: 3.8",
```suggestion
```

2023-11-01 21:15 UTC, jtherrmann submitted a review, later dismissed

2023-11-01 21:20 UTC, jtherrmann requested changes
We'll also need to update `environment.yml`. Also, does the `version` field in the Jupyter notebooks under `docs/` need to be updated? (I just ran a `git grep '3\.8'`.)

2023-11-01 21:31 UTC, jhkennedy commented
@jtherrmann I updated `environment.yml`.  The `version` field in the notebooks is just metadata recorded in the notebook about the Python version when it was run and checked into the repo. I don't see a need to update it, and it's not something you can every really see. It is possible to strip, albeit annoying to do so.

2023-11-01 21:32 UTC, jhkennedy commented on CHANGELOG.md
> +* The HyP3 SDK now explicitly supports python 3.8-3.12
```suggestion
* The HyP3 SDK now explicitly supports python 3.9-3.12
```

2023-11-01 21:32 UTC, jhkennedy commented on CHANGELOG.md
> +* The HyP3 SDK now explicitly supports python 3.9-3.12
```suggestion
* The HyP3 SDK now explicitly supports Python 3.9-3.12
```

2023-11-02 17:15 UTC, jtherrmann approved these changes

2023-11-02 17:25 UTC, merged